#pragma once

#include <mutex>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

#include "logos_token_manager_context.h"

// capability_module — the token authority, authored as a Qt-free UNIVERSAL
// module. Its public methods below ARE its API (the Qt-plugin glue + concurrent
// dispatch are generated by logos-module-builder).
//
// It derives LogosTokenManagerContext to reach two host services a normal
// module can't: reading the host's token store (getToken) and informing an
// ARBITRARY target module of a caller's token (informModuleToken). Both are
// bridged to the real LogosAPI/TokenManager by the generated cdylib provider.
//
// Runs under concurrency:"multi" — each dispatch executes on a worker thread, so
// m_restrictions is guarded by a mutex. This off-the-read-stack dispatch is the
// whole point: requestModule's outbound inform no longer re-enters the QtRO
// source read loop, which is what caused the historical CodecBase::send SIGSEGV.
class CapabilityModuleImpl : public LogosTokenManagerContext
{
public:
    /// Mint a token that lets `fromModuleName` call `moduleName`, and inform the
    /// target module of it. Returns the token, or "" on any rejection.
    std::string requestModule(const std::string& fromModuleName,
                              const std::string& moduleName);

    /// Register the exact set of callers allowed to reach `targetModule`. Only
    /// the trusted core/capability_module channel (proven by `authToken`) may
    /// call this. Returns true when the policy was accepted.
    bool registerRestriction(const std::string& authToken,
                             const std::string& targetModule,
                             const std::vector<std::string>& allowedCallers);

private:
    // target module -> set of caller modules allowed to reach it. A target
    // absent from this map is unrestricted (back-compat default). Guarded by
    // m_mutex because concurrency:"multi" dispatches requestModule (read) and
    // registerRestriction (write) on concurrent worker threads.
    std::unordered_map<std::string, std::unordered_set<std::string>> m_restrictions;
    mutable std::mutex m_mutex;
};
